---
abstract: 'Business Process Execution Engine'
author:
  - 'Peter de Vos, C<< <sitetech@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BPM-Engine
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  BPM::XPDL: 0.04
  Class::MOP: 1.1
  Class::Workflow: 0.11
  Config::Any: 0.23
  DBIx::Class: 0.08
  DBIx::Class::DynamicDefault: 0.03
  DBIx::Class::InflateColumn::Serializer: 0.02
  DBIx::Class::TimeStamp: 0.14
  DBIx::Class::UUIDColumns: 0.02
  Data::GUID: 0.046
  DateTime: 0.53
  Exception::Class: 1.29
  File::ShareDir: 1.03
  Graph: 0.94
  JSON: 0
  Moose: 2.0601
  MooseX::Declare: 0.35
  MooseX::LogDispatch: 1.20
  MooseX::Method::Signatures: 0.42
  MooseX::NonMoose: 0.22
  MooseX::SimpleConfig: 0.09
  MooseX::StrictConstructor: 0.07
  MooseX::Traits: 0.11
  MooseX::Types: 0.23
  MooseX::Types::DBIx::Class: 0.05
  MooseX::Types::UUID: 0.02
  Path::Class: 0.21
  Silly::Werder: 0.90
  Sub::Exporter: 0.98
  Template: 2.20
  Text::Xslate: 1.0012
  Text::Xslate::Bridge::TT2Like: 0
  Try::Tiny: 0.11
  XML::LibXML: 1.70
  XML::LibXML::Simple: 0.13
  YAML::LibYAML: 0.18
  aliased: 0
  namespace::autoclean: 0.11
  namespace::clean: 0.18
  parent: 0
  perl: 5.10.0
resources:
  homepage: http://bpmengine.org/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sitetechie/BPM-Engine.git
version: 0.01
